package com.dp.logcatapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005B52)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF008377)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF3E655F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC3EDE5)
val onSecondaryContainerLight = Color(0xFF28504A)
val tertiaryLight = Color(0xFF5D418A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8366B2)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAF8)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FAF8)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFD8E5E2)
val onSurfaceVariantLight = Color(0xFF3D4947)
val outlineLight = Color(0xFF6D7A77)
val outlineVariantLight = Color(0xFFBCC9C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3230)
val inverseOnSurfaceLight = Color(0xFFEDF2EF)
val inversePrimaryLight = Color(0xFF67D9C9)
val surfaceDimLight = Color(0xFFD6DBD9)
val surfaceBrightLight = Color(0xFFF5FAF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F2)
val surfaceContainerLight = Color(0xFFEAEFED)
val surfaceContainerHighLight = Color(0xFFE4E9E7)
val surfaceContainerHighestLight = Color(0xFFDEE4E1)
val currentSearchHitColorLight = Color(0xFFE5D754)

val primaryDark = Color(0xFF67D9C9)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF008377)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFA5CFC7)
val onSecondaryDark = Color(0xFF0C3731)
val secondaryContainerDark = Color(0xFF1E4640)
val onSecondaryContainerDark = Color(0xFFB3DDD5)
val tertiaryDark = Color(0xFFD6BAFF)
val onTertiaryDark = Color(0xFF3D2068)
val tertiaryContainerDark = Color(0xFF8366B2)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1413)
val onBackgroundDark = Color(0xFFDEE4E1)
val surfaceDark = Color(0xFF0F1413)
val onSurfaceDark = Color(0xFFDEE4E1)
val surfaceVariantDark = Color(0xFF3D4947)
val onSurfaceVariantDark = Color(0xFFBCC9C6)
val outlineDark = Color(0xFF869390)
val outlineVariantDark = Color(0xFF3D4947)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E1)
val inverseOnSurfaceDark = Color(0xFF2C3230)
val inversePrimaryDark = Color(0xFF006A60)
val surfaceDimDark = Color(0xFF0F1413)
val surfaceBrightDark = Color(0xFF353A39)
val surfaceContainerLowestDark = Color(0xFF0A0F0E)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1B211F)
val surfaceContainerHighDark = Color(0xFF252B2A)
val surfaceContainerHighestDark = Color(0xFF303635)
val currentSearchHitColorDark = Color(0xFF796A39)

object LogPriorityColors {
  val priorityAssert = Color(0xFF512DA8)
  val priorityDebug = Color(0xFF1976D2)
  val priorityError = Color(0xFFD32F2F)
  val priorityFatal = Color(0xFFC2185B)
  val priorityInfo = Color(0xFF388E3C)
  val prioritySilent = Color(0xFF616161)
  val priorityWarning = Color(0xFFE65100)
  val priorityVerbose = Color(0xFF546E7A)
}